-- Initial Schema Migration Script for Triple Triad Ninja
-- Run this on your Supabase SQL Editor to recreate the database structure

-- 1. Create PROFILES table
-- This table extends the default auth.users table with application-specific data
create table if not exists public.profiles (
  id uuid not null references auth.users on delete cascade,
  is_onboarded boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- 2. Create CARDS table
-- Stores the master list of all available cards
create table if not exists public.cards (
  id text not null primary key, -- Uses custom ID format e.g. 'fire-naruto-123'
  name text not null,
  element text not null,
  image_url text,
  description text,
  rarity text default 'common',
  is_init boolean default false, -- If true, can be obtained in starter pack
  cp integer default 0,
  stat_top integer default 0,
  stat_right integer default 0,
  stat_bottom integer default 0,
  stat_left integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for cards
alter table public.cards enable row level security;

-- Policies for cards
create policy "Cards are viewable by everyone."
  on public.cards for select
  using ( true );

create policy "Authenticated users can insert cards."
  on public.cards for insert
  with check ( auth.role() = 'authenticated' );

-- 3. Create USER_CARDS table
-- Links users to the cards they own
create table if not exists public.user_cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  card_id text not null references public.cards(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for user_cards
alter table public.user_cards enable row level security;

-- Policies for user_cards
create policy "Users can view their own cards."
  on public.user_cards for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own cards."
  on public.user_cards for insert
  with check ( auth.uid() = user_id );

-- 4. Setup Automation (Triggers)
-- Automatically create a profile entry when a new user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$$;

-- Drop trigger if exists to avoid conflicts on re-run
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
