import type { Metadata } from "next";
import { Geist, Geist_Mono, Shojumaru, Luckiest_Guy } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const shojumaru = Shojumaru({
  weight: "400",
  variable: "--font-shojumaru",
  subsets: ["latin"],
});
 
const luckiestGuy = Luckiest_Guy({
  weight: "400",
  variable: "--font-luckiest",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/components/AuthProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${shojumaru.variable} ${luckiestGuy.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
